### ISSUE TITLE
Question about the main instance

### ISSUE THREAD

**Issue by oifj34f34f** [TxtDot/txtdot#81]
txt.dc09.ru is located in Russia. How does it open sites such as BBC News, Meduza, SoundCloud and other sites blocked in Russia? Are you using [zapret](https://github.com/bol-van/zapret) or what?

**Comment by artegoser** [comment]
@DarkCat09

**Comment by DarkCat09** [comment]
@oifj34f34f,

Hello. No, currently I don't use any censorship circumvention techniques. BBC/Meduza/etc. is inaccessible from my server, so I would suggest you [Artegoser's](https://txt.artegoser.ru) or [Bloatcat's](https://txt.bloat.cat) instance.

I was thinking of a feature like letting a user specify a proxy URL, but this would make txtdot more complicated and, maybe, create pontential vulnerabilities.

As for "zapret", DPI bypassing won't help, because servers are blocked by IP address in most cases. I think I will setup a proxy for txtdot.

**Comment by artegoser** [comment]
But meduza is accessible

**Comment by oifj34f34f** [comment]
> Hello. No, currently I don't use any censorship circumvention techniques. BBC/Meduza/etc. is inaccessible from my server, so I would suggest you [Artegoser's](https://txt.artegoser.ru) or [Bloatcat's](https://txt.bloat.cat) instance.

But

[proof.webm](https://github.com/TxtDot/txtdot/assets/128177553/bf538c30-d900-415e-9f1c-b79f70137101)

> As for "zapret", DPI bypassing won't help, because servers are blocked by IP address in most cases. I think I will setup a proxy for txtdot.

I use it daily and it bypasses most sites, including the ones I listed. The exceptions are Twitter and Instagram as they are blocked by IP, but they won't display correctly anyway in Txtdot due to the heavy use of JavaScript

**Comment by oifj34f34f** [comment]
@DarkCat09 could you please reply to my message?

**Comment by DarkCat09** [comment]
That's weird. Meduza should not be available from Russian servers, but it is.

@oifj34f34f, okay, I'll consider using DPI bypassing. Thank you.
